"""Unit-level tests for the Cypher emitted by Neo4jVectorStore.query().

Asserts the generated Cypher uses the Cypher 25 ``SEARCH`` clause and
not the deprecated ``db.index.vector.queryNodes`` procedure. Lives
separate from ``test_neo4j_vector.py`` because that file is gated on a
live AuraDB connection — these are pure string-shape assertions on the
Cypher generated by a mock driver.
"""

from __future__ import annotations

from unittest.mock import MagicMock

import pytest

pytest.importorskip("neo4j")


def _capture_query_cypher(
    monkeypatch: pytest.MonkeyPatch,
    *,
    top_k: int = 10,
    filters: dict[str, object] | None = None,
    index_name: str = "trellis_node_embeddings",
    dimensions: int = 8,
) -> str:
    """Build a store with a mock driver and capture the query() Cypher."""
    monkeypatch.setattr(
        "trellis.stores.neo4j.vector.wait_for_vector_index_online",
        lambda *_, **__: None,
    )
    from trellis.stores.neo4j.vector import Neo4jVectorStore

    driver = MagicMock(name="driver")
    init_session = MagicMock(name="init_session")
    query_session = MagicMock(name="query_session")
    # Two distinct sessions over the lifetime: one for _init_schema, one
    # for the query() call. The MagicMock returns the same context
    # manager by default; that's fine — we only inspect query_session
    # via execute_read after the store is built.
    driver.session.return_value.__enter__.side_effect = [init_session, query_session]

    # Make execute_read invoke the lambda we feed it so we can spy on
    # the Cypher arg. The vector store routes reads through
    # ``Neo4jSessionRunner._run_read_list`` which calls
    # ``session.execute_read(lambda tx: list(tx.run(cypher, **params)))``.
    captured: dict[str, str] = {}

    def _capture(fn):
        tx = MagicMock(name="tx")
        # tx.run(cypher, **params) — we want the first positional arg.
        tx.run.return_value = []
        fn(tx)
        captured["cypher"] = str(tx.run.call_args.args[0])
        return []

    query_session.execute_read.side_effect = _capture

    store = Neo4jVectorStore(
        "bolt://x",
        user="u",
        driver=driver,
        dimensions=dimensions,
        index_name=index_name,
    )
    store.query([0.0] * dimensions, top_k=top_k, filters=filters)
    return captured["cypher"]


class TestQueryCypherUsesSearchClause:
    def test_uses_search_clause_not_deprecated_procedure(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        cypher = _capture_query_cypher(monkeypatch)
        # Headline assertion: deprecated procedure is gone.
        assert "db.index.vector.queryNodes" not in cypher
        # Cypher 25 SEARCH clause shape — the parts that prove migration.
        assert "SEARCH n IN" in cypher
        assert "VECTOR INDEX trellis_node_embeddings FOR $vector" in cypher
        assert "SCORE AS score" in cypher

    def test_index_name_inlined_as_cypher_literal(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        # The VECTOR INDEX ref is a literal — not a $-bound parameter —
        # so a custom index name has to flow through unquoted.
        cypher = _capture_query_cypher(monkeypatch, index_name="custom_idx")
        assert "VECTOR INDEX custom_idx FOR $vector" in cypher

    def test_post_where_filters_historical_versions(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        # ``valid_to IS NULL`` MUST live AFTER the SEARCH block — vector
        # indexes only honour properties registered as filter properties
        # at CREATE time, and we don't register valid_to. Confirmed
        # against AuraDB live (see migration commit).
        cypher = _capture_query_cypher(monkeypatch)
        search_close = cypher.index(") SCORE AS score")
        post_where = cypher.index("WHERE n.valid_to IS NULL")
        assert post_where > search_close

    def test_overfetch_with_filters(self, monkeypatch: pytest.MonkeyPatch) -> None:
        # Sanity: filters present ⇒ over-fetch by _OVER_FETCH_MULT (10x).
        # The factor lives in vector.py — assert behaviourally via the
        # bound ``k`` parameter rather than scraping the constant.
        from trellis.stores.neo4j.vector import _OVER_FETCH_MULT

        captured: dict[str, int] = {}

        def _spy_for_k(monkeypatch_inner: pytest.MonkeyPatch) -> None:
            monkeypatch_inner.setattr(
                "trellis.stores.neo4j.vector.wait_for_vector_index_online",
                lambda *_, **__: None,
            )
            from trellis.stores.neo4j.vector import Neo4jVectorStore

            driver = MagicMock(name="driver")
            init_session = MagicMock(name="init_session")
            query_session = MagicMock(name="query_session")
            driver.session.return_value.__enter__.side_effect = [
                init_session,
                query_session,
            ]

            def _capture_params(fn):
                tx = MagicMock(name="tx")
                tx.run.return_value = []
                fn(tx)
                captured["k"] = int(tx.run.call_args.kwargs["k"])
                return []

            query_session.execute_read.side_effect = _capture_params

            store = Neo4jVectorStore("bolt://x", user="u", driver=driver, dimensions=4)
            store.query([0.0, 0.0, 0.0, 0.0], top_k=5, filters={"node_type": "doc"})

        _spy_for_k(monkeypatch)
        assert captured["k"] == 5 * _OVER_FETCH_MULT
