"""Tests for the Measurement Pydantic schema.

Schema is defined in ``src/trellis/schemas/measurement.py``. Sibling
Observation tests live in ``test_observation.py``.
"""

from __future__ import annotations

from datetime import UTC, datetime

import pytest
from pydantic import ValidationError

from trellis.schemas import Measurement
from trellis.schemas import well_known as wk


def _valid_kwargs() -> dict[str, object]:
    return {
        "subject_entity_id": "entity_abc",
        "subject_entity_type": wk.DATASET,
        "metric_name": "null_rate",
        "metric_value": 0.03,
        "observer_agent_id": "agent_test",
    }


class TestMeasurementRequiredFields:
    def test_minimal_valid_construction(self) -> None:
        m = Measurement(**_valid_kwargs())  # type: ignore[arg-type]
        assert m.subject_entity_id == "entity_abc"
        assert m.metric_name == "null_rate"
        assert m.metric_value == 0.03
        assert m.observer_agent_id == "agent_test"
        assert m.unit is None

    @pytest.mark.parametrize(
        "missing_field",
        [
            "subject_entity_id",
            "subject_entity_type",
            "metric_name",
            "metric_value",
            "observer_agent_id",
        ],
    )
    def test_missing_required_field_raises(self, missing_field: str) -> None:
        kwargs = _valid_kwargs()
        kwargs.pop(missing_field)
        with pytest.raises(ValidationError):
            Measurement(**kwargs)  # type: ignore[arg-type]

    def test_extra_field_forbidden(self) -> None:
        kwargs = _valid_kwargs()
        kwargs["bogus_extra_field"] = "x"
        with pytest.raises(ValidationError):
            Measurement(**kwargs)  # type: ignore[arg-type]


class TestMeasurementValueTypes:
    @pytest.mark.parametrize("value", [0.0, 0.5, 1.0, 999.9, -1.0, 1e9])
    def test_metric_value_accepts_floats(self, value: float) -> None:
        m = Measurement(**{**_valid_kwargs(), "metric_value": value})  # type: ignore[arg-type]
        assert m.metric_value == value

    def test_unit_optional(self) -> None:
        m = Measurement(**{**_valid_kwargs(), "unit": "percent"})  # type: ignore[arg-type]
        assert m.unit == "percent"


class TestMeasurementDatetime:
    def test_measured_at_accepts_datetime(self) -> None:
        when = datetime(2026, 5, 12, 8, 30, tzinfo=UTC)
        m = Measurement(**{**_valid_kwargs(), "measured_at": when})  # type: ignore[arg-type]
        assert m.measured_at == when

    def test_measured_at_accepts_iso_string(self) -> None:
        iso = "2026-05-12T08:30:00+00:00"
        m = Measurement(**{**_valid_kwargs(), "measured_at": iso})  # type: ignore[arg-type]
        assert m.measured_at == datetime(2026, 5, 12, 8, 30, tzinfo=UTC)

    def test_measured_at_defaults_to_now(self) -> None:
        before = datetime.now(tz=UTC)
        m = Measurement(**_valid_kwargs())  # type: ignore[arg-type]
        after = datetime.now(tz=UTC)
        assert before <= m.measured_at <= after


class TestMeasurementIdGeneration:
    def test_measurement_id_autogenerated(self) -> None:
        m1 = Measurement(**_valid_kwargs())  # type: ignore[arg-type]
        m2 = Measurement(**_valid_kwargs())  # type: ignore[arg-type]
        assert m1.measurement_id
        assert m2.measurement_id
        assert m1.measurement_id != m2.measurement_id
        assert len(m1.measurement_id) == 26

    def test_measurement_id_preserved_when_supplied(self) -> None:
        m = Measurement(
            **{**_valid_kwargs(), "measurement_id": "custom_meas_7"}  # type: ignore[arg-type]
        )
        assert m.measurement_id == "custom_meas_7"


class TestMeasurementRoundTrip:
    def test_json_round_trip(self) -> None:
        original = Measurement(
            **{  # type: ignore[arg-type]
                **_valid_kwargs(),
                "unit": "percent",
                "metadata": {
                    "window_start": "2026-05-01T00:00:00+00:00",
                    "window_end": "2026-05-11T23:59:59+00:00",
                    "sample_size": 10_000,
                },
                "measured_at": datetime(2026, 5, 12, 8, 30, tzinfo=UTC),
            }
        )
        as_json = original.model_dump_json()
        restored = Measurement.model_validate_json(as_json)
        assert restored == original
        assert restored.unit == "percent"
        assert restored.metadata is not None
        assert restored.metadata["sample_size"] == 10_000
