"""Tests for the Observation Pydantic schema.

Schema is defined in ``src/trellis/schemas/observation.py``. Companion
Measurement tests live in ``test_measurement.py``; well-known
registration tests (canonicalization, alignment URI, version) live in
``test_well_known.py``.
"""

from __future__ import annotations

from datetime import UTC, datetime

import pytest
from pydantic import ValidationError

from trellis.schemas import Observation
from trellis.schemas import well_known as wk


# Minimal kwargs for a valid Observation. Tests start from this and
# mutate one field at a time.
def _valid_kwargs() -> dict[str, object]:
    return {
        "subject_entity_id": "entity_abc",
        "subject_entity_type": wk.DATASET,
        "observer_agent_id": "agent_test",
        "content": "column X is filtered in 95% of queries",
        "confidence": 0.9,
    }


class TestObservationRequiredFields:
    def test_minimal_valid_construction(self) -> None:
        obs = Observation(**_valid_kwargs())  # type: ignore[arg-type]
        assert obs.subject_entity_id == "entity_abc"
        assert obs.subject_entity_type == "Dataset"
        assert obs.observer_agent_id == "agent_test"
        assert obs.confidence == 0.9

    @pytest.mark.parametrize(
        "missing_field",
        [
            "subject_entity_id",
            "subject_entity_type",
            "observer_agent_id",
            "content",
            "confidence",
        ],
    )
    def test_missing_required_field_raises(self, missing_field: str) -> None:
        kwargs = _valid_kwargs()
        kwargs.pop(missing_field)
        with pytest.raises(ValidationError):
            Observation(**kwargs)  # type: ignore[arg-type]

    def test_extra_field_forbidden(self) -> None:
        # TrellisModel inherits ``extra="forbid"``; unknown fields must
        # raise per CLAUDE.md hard rules.
        kwargs = _valid_kwargs()
        kwargs["bogus_extra_field"] = "x"
        with pytest.raises(ValidationError):
            Observation(**kwargs)  # type: ignore[arg-type]


class TestObservationConfidenceRange:
    @pytest.mark.parametrize("good", [0.0, 0.5, 1.0])
    def test_confidence_in_range(self, good: float) -> None:
        obs = Observation(**{**_valid_kwargs(), "confidence": good})  # type: ignore[arg-type]
        assert obs.confidence == good

    @pytest.mark.parametrize("bad", [-0.1, 1.01, 2.0, -1.0])
    def test_confidence_out_of_range(self, bad: float) -> None:
        with pytest.raises(ValidationError):
            Observation(**{**_valid_kwargs(), "confidence": bad})  # type: ignore[arg-type]


class TestObservationDatetime:
    def test_observed_at_accepts_datetime(self) -> None:
        when = datetime(2026, 5, 12, 8, 30, tzinfo=UTC)
        obs = Observation(**{**_valid_kwargs(), "observed_at": when})  # type: ignore[arg-type]
        assert obs.observed_at == when

    def test_observed_at_accepts_iso_string(self) -> None:
        iso = "2026-05-12T08:30:00+00:00"
        obs = Observation(**{**_valid_kwargs(), "observed_at": iso})  # type: ignore[arg-type]
        assert obs.observed_at == datetime(2026, 5, 12, 8, 30, tzinfo=UTC)

    def test_observed_at_defaults_to_now(self) -> None:
        before = datetime.now(tz=UTC)
        obs = Observation(**_valid_kwargs())  # type: ignore[arg-type]
        after = datetime.now(tz=UTC)
        assert before <= obs.observed_at <= after


class TestObservationIdGeneration:
    def test_observation_id_autogenerated(self) -> None:
        obs1 = Observation(**_valid_kwargs())  # type: ignore[arg-type]
        obs2 = Observation(**_valid_kwargs())  # type: ignore[arg-type]
        assert obs1.observation_id
        assert obs2.observation_id
        assert obs1.observation_id != obs2.observation_id
        # ULID is 26 characters.
        assert len(obs1.observation_id) == 26

    def test_observation_id_preserved_when_supplied(self) -> None:
        obs = Observation(
            **{**_valid_kwargs(), "observation_id": "custom_id_42"}  # type: ignore[arg-type]
        )
        assert obs.observation_id == "custom_id_42"


class TestObservationRoundTrip:
    def test_json_round_trip(self) -> None:
        original = Observation(
            **{  # type: ignore[arg-type]
                **_valid_kwargs(),
                "evidence_ref": "trace_xyz",
                "metadata": {"kind": "filter_rate", "sample_size": 1000},
                "observed_at": datetime(2026, 5, 12, 8, 30, tzinfo=UTC),
            }
        )
        as_json = original.model_dump_json()
        restored = Observation.model_validate_json(as_json)
        assert restored == original
        assert restored.evidence_ref == "trace_xyz"
        assert restored.metadata == {"kind": "filter_rate", "sample_size": 1000}

    def test_metadata_optional_defaults_to_none(self) -> None:
        obs = Observation(**_valid_kwargs())  # type: ignore[arg-type]
        assert obs.metadata is None
        assert obs.evidence_ref is None
