"""Where advisories come from — the one home for resolving and loading them.

Advisories are generated by a batch analyzer and consumed by pack
assembly, and until #373 the two halves did not agree on a filename.
The nightly worker and ``trellis analyze`` wrote ``<data_dir>/advisories.json``;
the MCP pack builder, the REST pack builder and the REST admin routes read
``<stores_dir>/advisories.json``. On the reference deployment the writers'
file held **37 advisories refreshed nightly for 17 days** and the readers'
file did not exist, so every pack ever assembled was assembled as though no
advisory had ever been generated.

This module is the seam that makes that impossible to reintroduce. It
answers one question — *given a deployment's store directory, which
advisory file is it using?* — and it is the only place that answers it.
Every writer and every reader resolves through :func:`resolve_advisory_path`,
so the file the worker writes is by construction the file the pack builder
reads.

Declared location
-----------------
``<stores_dir>/advisories.json`` — co-located with the rest of the store
state (``api_keys.db``, ``outcomes.db``, ``parameters.db``,
``policies.json``), which is where the REST admin routes and the advisory
integration test already looked. ``stores_dir`` is ``<data_dir>/stores``,
so with default configuration that is
``~/.trellis/data/stores/advisories.json``.

**Legacy path.** ``<data_dir>/advisories.json`` is honoured, with a warning
naming both paths. This is not a formality: on the reference deployment the
legacy path is the *live* one, written nightly by cron, and the canonical
one has never existed. Resolution is therefore symmetric — a reader and a
writer on the same deployment resolve the same file — so honouring the
legacy path keeps the nightly worker writing where it already writes
instead of silently starting a second file and splitting the state again.
The canonical path wins when both exist, and a deployment with neither gets
the canonical path back so fresh installs create the right file.

Migration is the operator's call, not this module's: nothing here moves,
copies or rewrites an existing file.

Default posture
---------------
:func:`load_advisory_store` **always returns a store — never ``None``**.
That is the whole point. The three readers previously wrote::

    adv_path = stores_dir / "advisories.json"
    if adv_path.exists():
        advisory_store = AdvisoryStore(adv_path)

and a misresolved path fell through that guard into ``advisory_store =
None``, which :class:`~trellis.retrieve.pack_builder.PackBuilder` treats as
"this deployment has no advisories". A wrong directory and an empty
deployment were indistinguishable, in silence, for weeks. Removing the
``None`` branch removes the failure mode structurally: an absent file
yields an *empty* store, which is behaviourally identical to the old
``None`` (``AdvisoryStore.list()`` returns ``[]``) but leaves a log line
naming every path that was searched.

Failure posture
---------------
**Reading is lenient; writing is not.** Those are two questions, and #393
is what happens when one answer is given to both.

The read is deliberately unlike :mod:`trellis.mutate.policy_source`, which
raises on a malformed policy file. A policy file governs access control, so
degrading it to "no policies" silently disables a guarantee the caller
believes it has. Advisories are hint-only guidance attached to a pack; a
corrupt advisory file must not take retrieval down with it. So
:func:`load_advisory_store` still always returns a store, constructing one
never raises, and a partially-readable file yields the rows that parsed.

But :class:`AdvisoryStore` whole-file-rewrites on every write, so the same
leniency applied to the write *deletes* the file it could not read — and
since stable advisory ids (#394), silently revives every advisory the
fitness loop had suppressed. A store that loaded degraded therefore
refuses every write (:class:`~trellis.errors.DegradedStoreWriteError`)
while continuing to serve. See :mod:`trellis.stores.advisory_store` for the
full argument and for why recovery is left to the operator.

This module's job in that is to make the degradation *visible at the read
surfaces* — MCP pack assembly, the REST retrieve route, the admin routes —
which is where a corrupt file otherwise looks exactly like a deployment
that has never generated an advisory.
"""

from __future__ import annotations

from pathlib import Path
from typing import overload

import structlog

from trellis.stores.advisory_store import AdvisoryStore

logger = structlog.get_logger(__name__)

#: Filename holding a deployment's generated advisories, under ``stores_dir``.
ADVISORY_FILENAME = "advisories.json"


@overload
def resolve_advisory_path(stores_dir: Path) -> Path: ...


@overload
def resolve_advisory_path(stores_dir: None) -> None: ...


def resolve_advisory_path(stores_dir: Path | None) -> Path | None:
    """Return the advisory file a deployment should read and write.

    Prefers the canonical ``<stores_dir>/advisories.json``. Falls back to
    the legacy ``<data_dir>/advisories.json`` (i.e. ``stores_dir``'s
    parent) only when the canonical file is absent and the legacy file
    exists, warning with both paths so the operator can migrate.

    Returns ``None`` when ``stores_dir`` is ``None`` — an in-memory or
    programmatically-constructed registry has no directory to read, and
    that is a normal case meaning "no advisories", not an error.
    """
    if stores_dir is None:
        return None

    canonical = Path(stores_dir) / ADVISORY_FILENAME
    if canonical.exists():
        return canonical

    legacy = Path(stores_dir).parent / ADVISORY_FILENAME
    if legacy.exists():
        logger.warning(
            "advisory_file_at_legacy_path",
            legacy_path=str(legacy),
            canonical_path=str(canonical),
            hint=(
                "Advisories were found at the pre-unification writer path. "
                "They are being honoured, but move the file to the canonical "
                "path — a future release may stop looking at the legacy "
                "location."
            ),
        )
        return legacy

    # Neither exists: hand back the canonical path so writers create the
    # right file. Readers get an empty store and a log line (see
    # ``load_advisory_store``).
    return canonical


def load_advisory_store(
    stores_dir: Path | None,
    *,
    surface: str,
) -> AdvisoryStore | None:
    """Open a deployment's advisory store, logging what was found.

    Returns an :class:`AdvisoryStore` whenever ``stores_dir`` is
    configured — an *empty* one when no advisory file exists, never
    ``None``. ``None`` comes back only when ``stores_dir`` itself is
    ``None``, which means the deployment has no directory to read at all.

    Args:
        stores_dir: The registry's ``stores_dir``, or ``None``.
        surface: Which caller is loading — ``"mcp"``, ``"api.retrieve"``,
            ``"cli.worker"``, and so on. It rides the log line so an
            operator reading the journal can tell *which* surface saw
            what, which is the question that went unanswered for the whole
            life of #373.

    The absent-file case logs at ``info`` rather than ``warning`` on
    purpose: a greenfield deployment genuinely has no advisories and a
    warning on every pack assembly would cry wolf. What makes it
    diagnosable is not the level but the content — the line names every
    path that was searched, so "no advisories here" and "looking in the
    wrong directory" no longer present identically.

    A *degraded* file is the opposite case and gets ``warning``: it is not
    normal, it is not self-correcting, and the store it returns will refuse
    every write until an operator acts. The returned store is still usable
    for reads, so callers need not branch on it — pack assembly carries on
    with whatever parsed.
    """
    if stores_dir is None:
        logger.info("advisory_store_unconfigured", surface=surface)
        return None

    # ``stores_dir`` is narrowed to ``Path`` here, so the overload gives
    # back a ``Path`` rather than ``Path | None`` — no narrowing needed.
    path = resolve_advisory_path(stores_dir)

    if not path.exists():
        logger.info(
            "advisory_file_absent",
            surface=surface,
            searched=[
                str(Path(stores_dir) / ADVISORY_FILENAME),
                str(Path(stores_dir).parent / ADVISORY_FILENAME),
            ],
            detail=(
                "No advisory file at either the canonical or the legacy "
                "path. Packs will carry no advisories. This is normal for a "
                "deployment that has never run `trellis analyze "
                "generate-advisories`."
            ),
        )
        return AdvisoryStore(path)

    store = AdvisoryStore(path)
    degradation = store.degradation
    if degradation is not None:
        # The store has already logged the failure in detail. This line
        # exists to attach the *surface* to it: "advisories are degraded"
        # and "the MCP pack builder is serving degraded advisories" are
        # different facts, and only the second tells an operator what their
        # agents are actually getting. ``warning`` rather than ``info``
        # because the CLI pins WARNING by default — see
        # ``trellis_cli.main._root`` — so an info line would be invisible on
        # the surface that runs nightly.
        logger.warning(
            "advisory_store_degraded",
            surface=surface,
            **degradation.to_dict(),
            servable_count=len(store.list()),
        )
        return store

    logger.info(
        "advisory_store_loaded",
        surface=surface,
        path=str(path),
        advisory_count=len(store.list(include_suppressed=True)),
        servable_count=len(store.list()),
    )
    return store
