"""Retrieval system for Trellis pack assembly."""

from trellis.retrieve.evaluate import (
    BUILTIN_PROFILES,
    CODE_GENERATION_PROFILE,
    DEFAULT_DIMENSIONS,
    DOMAIN_CONTEXT_PROFILE,
    BreadthScorer,
    CompletenessScorer,
    DimensionPredictiveness,
    DimensionPredictivenessReport,
    EfficiencyScorer,
    EvaluationProfile,
    EvaluationScenario,
    NoiseScorer,
    QualityDimension,
    QualityReport,
    RelevanceScorer,
    ShapeCompositionScorer,
    ShapeConstraint,
    analyze_dimension_predictiveness,
    evaluate_pack,
)
from trellis.retrieve.excerpts import (
    CONTENT_FLOOR_REJECTION_REASON,
    DEFAULT_CONTENT_FLOOR,
    DEFAULT_CONTENT_FLOOR_PENALTY,
    DEFAULT_FLOOR_EXEMPT_ITEM_TYPES,
    DEFAULT_MIN_DISTINCT_WORDS,
    EXCERPT_ELLIPSIS,
    EXCERPT_MAX_CHARS,
    ContentFloorConfig,
    ContentFloorMode,
    ContentFloorResult,
    apply_content_floor,
    count_substance_words,
    truncate_excerpt,
)
from trellis.retrieve.observation_strategy import ObservationSearch
from trellis.retrieve.pack_builder import (
    PackAssemblyError,
    PackBuilder,
    PackEvaluator,
    SemanticDedupConfig,
    StrategyFailure,
)
from trellis.retrieve.strategies import (
    GraphSearch,
    KeywordSearch,
    SearchStrategy,
    SemanticSearch,
)
from trellis.retrieve.telemetry import (
    KNOWN_REJECTION_REASONS,
    PackTelemetryReport,
    StrategyContribution,
    analyze_pack_telemetry,
)
from trellis.retrieve.tier_mapping import TierMapper
from trellis.retrieve.token_counting import (
    DEFAULT_TOKEN_COUNTER,
    HeuristicTokenCounter,
    TokenCounter,
)

__all__ = [
    "BUILTIN_PROFILES",
    "CODE_GENERATION_PROFILE",
    "CONTENT_FLOOR_REJECTION_REASON",
    "DEFAULT_CONTENT_FLOOR",
    "DEFAULT_CONTENT_FLOOR_PENALTY",
    "DEFAULT_DIMENSIONS",
    "DEFAULT_FLOOR_EXEMPT_ITEM_TYPES",
    "DEFAULT_MIN_DISTINCT_WORDS",
    "DEFAULT_TOKEN_COUNTER",
    "DOMAIN_CONTEXT_PROFILE",
    "EXCERPT_ELLIPSIS",
    "EXCERPT_MAX_CHARS",
    "BreadthScorer",
    "CompletenessScorer",
    "ContentFloorConfig",
    "ContentFloorMode",
    "ContentFloorResult",
    "DimensionPredictiveness",
    "DimensionPredictivenessReport",
    "EfficiencyScorer",
    "EvaluationProfile",
    "EvaluationScenario",
    "GraphSearch",
    "HeuristicTokenCounter",
    "KNOWN_REJECTION_REASONS",
    "KeywordSearch",
    "NoiseScorer",
    "ObservationSearch",
    "PackAssemblyError",
    "PackBuilder",
    "PackEvaluator",
    "PackTelemetryReport",
    "QualityDimension",
    "QualityReport",
    "RelevanceScorer",
    "SearchStrategy",
    "SemanticDedupConfig",
    "SemanticSearch",
    "ShapeCompositionScorer",
    "ShapeConstraint",
    "StrategyContribution",
    "StrategyFailure",
    "TierMapper",
    "TokenCounter",
    "analyze_dimension_predictiveness",
    "analyze_pack_telemetry",
    "apply_content_floor",
    "count_substance_words",
    "evaluate_pack",
    "truncate_excerpt",
]
